### ISSUE TITLE
New sandbox id doesn't work

### ISSUE THREAD

**Issue by allenylzhou** [square/react-square-payment-form#23]
The token call when the SqPaymentForm is initialized consistently returns 401 unauthorized when using a new (non-legacy) sandbox application id.

**Comment by allenylzhou** [comment]
The URL is https://pci-connect.squareup.com/v2/card-nonce?version=85a1419eb2&_=1567463683109.9197

**Comment by mootrichard** [comment]
I found out why this is happening. There is actually an undocumented prop for `SquarePaymentForm` for `sandbox` that you need to set `sandbox={true}` in order for it to target the Sandbox.

I guess it would be possible to just parse the Application ID for whether the in contains `"sandbox"` if we wanted to be clever about it. 

For now, you just need to set that boolean prop on `SquarePaymentForm`

**Comment by mootrichard** [comment]
Also looks like this should be fixed by #24

**Comment by stephtaylor** [comment]
It looks like v0.3.0 (sandbox support) was published, but the changes didn't make it to the doc sites. This should be fixed in the new v0.4.0 release.
