### ISSUE TITLE
Missing props from samples

### ISSUE THREAD

**Issue by gregdegruy** [square/react-square-payment-form#50]
The props `formId` and `locationId` for the `SquarePaymentForm` are required, but the [samples](https://square.github.io/react-square-payment-form/docs/paymentform) here https://square.github.io/react-square-payment-form/docs/paymentform do not include them.

**Comment by stephtaylor** [comment]
`locationId` is called out here: https://square.github.io/react-square-payment-form/docs/paymentform#5-add-the-squarepaymentform

`formId` is required, but doesn't need to be explicitly passed in unless you're rendering multiple payment forms: https://square.github.io/react-square-payment-form/docs/customization#render-multiple-payment-forms

Closing this for now, but please let us know if there's a way to make the docs more clear.
