### ISSUE TITLE
SquarePaymentForm is loading very slowly

### ISSUE THREAD

**Issue by pavinduLakshan** [square/react-square-payment-form#57]
I have my payment form inside a modal window. When I open the modal, it takes about 15 seconds to fully load the payment form. It will be great if that can be fixed,

**Comment by DavidRagone** [comment]
Yikes, sorry to hear that. Can you provide more details from the Network tab (in Chrome, or equivalent in other browsers) regarding all requests to squareup.com?

E.g., here's what I see

![image](https://user-images.githubusercontent.com/1452099/79881598-409c0d00-83a6-11ea-8f3a-519e454f5791.png)

**Comment by pavinduLakshan** [comment]
Here is what I see.  Please have a look at that.

![square_slow](https://user-images.githubusercontent.com/41533942/79884895-80e5a480-8413-11ea-9c5b-7bb226429f6f.PNG)

**Comment by pavinduLakshan** [comment]
Some iframes are taking about 4s to load. I turned off adblocker and tried it, but it wasn't resolved

**Comment by DavidRagone** [comment]
Do you mind if I ask where you're located? We have noticed some oddness with load times in certain regions

**Comment by pavinduLakshan** [comment]
@DavidRagone Yes you are correct..I'm from Sri Lanka and only today I got to know that Square doesn't operate in the Asian region for now. That may be the reason for slow loading.. I will close the issue. anyways, thanks for your kind and supportive response.

**Comment by DavidRagone** [comment]
Yeah, I'm sorry to say we're not there yet. Given that someone could buy from anywhere in the world, improving speeds globally is definitely something we're looking at.
