### ISSUE TITLE
errors in the cardNonceResponseReceived leads the if statement always true. 

### ISSUE THREAD

**Issue by imgarylai** [square/react-square-payment-form#58]
https://github.com/square/react-square-payment-form/blob/c11114bbf655e3aa4ddaf8d6ab8a0e311bb133b6/demo/src/PaymentPage.jsx#L21-L31

This React square payment form is awesome. Thank you, @square team. 

I have a question regarding the function `cardNonceResponseReceived`. It is about the `errors` argument.

If the `errors` argument returned from the square and passed to `cardNonceResponseReceived` function is an array with null, `[null]`, does it mean there is an error but we don't know what kind of error happened? Or does it mean that there is no error, so it is an array but only have a `null` object? I believe the second case is right. If it is an array but only have a `null` object, it should be no error, right? 

In the second case, if my assumption is right, should we change the if statement to `if (errors && errors [0] != null)`? because it is always true when `errors` are `[null]`. 

Please let me know if you have any problems with my question! 

Thanks

**Comment by calebfaruki** [comment]
Also having this issue. My assumption is that the array should be empty, so I filter out the null.

**Comment by stephtaylor** [comment]
Thanks for pointing this out! The errors returned should be `null` or `[error]`, not `[null]`. This should be fixed in the next release.
