### ISSUE TITLE
Cannot call SqPaymentForm#requestCardNonce before the paymentFormLoaded() callback

### ISSUE THREAD

**Issue by rozzamozza** [square/react-square-payment-form#68]
I Suspect the <SquarePaymentForm is rendered multiple times.

This occasionally results in the following error when clicking Pay:

Uncaught FormNotReadyError: Cannot call SqPaymentForm#requestCardNonce before the paymentFormLoaded() callback. See Step 4: https://developer.squareup.com/docs/payment-form/how-it-works#the-sqpaymentform-process-flow
    at bt (https://js.squareupsandbox.com/v2/paymentform:1:154363)

Console logs.

paymentFormLoaded()

VM3396 0.chunk.js:55739 [Analytics] A token request is already in place
console.<computed> @ VM3396 0.chunk.js:55739
overrideMethod @ VM3411 react_devtools_backend.js:2273
s.getToken @ VM3413 data.js:10
(anonymous) @ VM3398 paymentform:1
_processQueue @ VM3398 paymentform:1
_handleLoad @ VM3398 paymentform:1
i @ VM3398 paymentform:1
load (async)
_injectScript @ VM3398 paymentform:1
t @ VM3398 paymentform:1
load (async)
_install @ VM3398 paymentform:1
calculate @ VM3398 paymentform:1
e @ VM3398 paymentform:1
mt._requestAnalyticsToken @ VM3398 paymentform:1
mt @ VM3398 paymentform:1
St._initialize @ VM3398 paymentform:1
St @ VM3398 paymentform:1
renderSqPaymentForm @ VM3396 0.chunk.js:66133
(anonymous) @ VM3396 0.chunk.js:66152
commitHookEffectListMount @ VM3396 0.chunk.js:49068
commitPassiveHookEffects @ VM3396 0.chunk.js:49105
callCallback @ VM3396 0.chunk.js:29650
invokeGuardedCallbackDev @ VM3396 0.chunk.js:29699
invokeGuardedCallback @ VM3396 0.chunk.js:29752
flushPassiveEffectsImpl @ VM3396 0.chunk.js:52169
unstable_runWithPriority @ VM3396 0.chunk.js:70962
runWithPriority$1 @ VM3396 0.chunk.js:40537
flushPassiveEffects @ VM3396 0.chunk.js:52137
(anonymous) @ VM3396 0.chunk.js:52016
workLoop @ VM3396 0.chunk.js:70906
flushWork @ VM3396 0.chunk.js:70862
performWorkUntilDeadline @ VM3396 0.chunk.js:70466
VM3398 paymentform:1 Uncaught FormNotReadyError: Cannot call SqPaymentForm#requestCardNonce before the paymentFormLoaded() callback. See Step 4: https://developer.squareup.com/docs/payment-form/how-it-works#the-sqpaymentform-process-flow
    at bt (https://js.squareupsandbox.com/v2/paymentform:1:154363)
    at Pt (https://js.squareupsandbox.com/v2/paymentform:1:163861)

**Comment by rozzamozza** [comment]
Related to <React.StrictMode>
Which ends up rendering twice...
https://mariosfakiolas.com/blog/my-react-components-render-twice-and-drive-me-crazy/

Workaround is to remove <React.StrictMode> but be good if we could keep using...

**Comment by stephtaylor** [comment]
Hi @rozzamozza, do you have an example of how you're rendering the SquarePaymentForm in your app? Are you doing any conditional rendering of the form?

**Comment by rozzamozza** [comment]
I’ll close this.fixed.  My Problem was I had a second instance of the payment form displayed. 

The don replacement was only replacing the first form. 

I still have an issue where the cvv On separate form is not auto populated Using autocomplete.  (even on chrome when choosing a saved card ) but will raise as separate issue.
