### ISSUE TITLE
Support Gift Card payment form

### ISSUE THREAD

**Issue by spenweb** [square/react-square-payment-form#71]
Gift card payment support needs to be implemented in order for this project to be a complete React TypeScript solution.

[Link to vanilla JavaScript implementation per the Square docs](https://developer.squareup.com/docs/payment-form/gift-cards/part-1)

**Comment by Xabadu** [comment]
Hey @spenweb, thanks for reaching out!

Support for this will be added in #77.

Let us know if you have any questions!
