### ISSUE TITLE
Support calling setPostalCode

### ISSUE THREAD

**Issue by njoyce** [square/react-square-payment-form#78]
I'm trying to call ``setPostalCode`` in the ``paymentFormLoaded`` callback. Problem is, the ``SqPaymentForm`` instance is hidden in a closure and there is no obvious/documented way to access it.

Additionally, there does not appear to be a way to provide the default value for the postal code via props/context. Any pointers or ideas would be appreciated.

See related [forum post](https://developer.squareup.com/forums/t/calling-setpostalcode-using-react-square-payment-form/823).

**Comment by Xabadu** [comment]
Hi @njoyce, thanks for reaching out.

We're adding support for this in #75. With that, you will be able to add a new `postalCode` prop and pass a callback to return the postal code you want to set (and add any logic you need to inside there as well).

Please let us know if you have any questions!
