### ISSUE TITLE
When trying to run the demo the card UI doesn't have input fields

### ISSUE THREAD

**Issue by HarounAns** [square/react-square-payment-form#81]
![image](https://user-images.githubusercontent.com/20847319/92310810-c39db880-ef7f-11ea-9756-0370df98c960.png)

I tried running the demo as is, and then I tried following this guide https://square.github.io/react-square-payment-form/docs/paymentform with create react app, but in both cases I got the picture above. There is no way to actually input a credit card number or any of the other fields

**Comment by Xabadu** [comment]
Hey @HarounAns,

Thanks for reaching out. Do you have a copy of your project published that you could share with us? Happy to take a look and help with this. If not, do you mind publishing and sharing the link with us? (If you need a tool to help with this, creating a  [Sandbox](https://codesandbox.io/) might be helpful)

**Comment by spenweb** [comment]
I am also experiencing this. With the latest release (v0.7.0), the Square payment form remote js script is no longer being loaded, thus no iFrames are created to receive credit card info.

**Comment by spenweb** [comment]
This bug seems to be due to this commit removing the statement that appends the script to the document:
https://github.com/square/react-square-payment-form/commit/cb6d04116b9cdadf93ad7405a1d5db15f035c3dd#diff-62481efeab60b6a2fc21d34271288c3fL205

In the previous commit, the script was being appended to the document. It is no longer. Here is the previous commit line:
https://github.com/square/react-square-payment-form/blob/27533de09bc192ed4b60ffbdb2d40dd248e0de65/src/components/SquarePaymentForm.tsx#L205

**Comment by HarounAns** [comment]
> Hey @HarounAns,
> 
> Thanks for reaching out. Do you have a copy of your project published that you could share with us? Happy to take a look and help with this. If not, do you mind publishing and sharing the link with us? (If you need a tool to help with this, creating a [Sandbox](https://codesandbox.io/) might be helpful).

I literally clone the demo, changed into the demo directory. Npm installed and npm started it and got the issue. I think @spenweb's change should fix it

**Comment by HarounAns** [comment]
> This bug seems to be due to this commit removing the statement that appends the script to the document:
> [cb6d041#diff-62481efeab60b6a2fc21d34271288c3fL205](https://github.com/square/react-square-payment-form/commit/cb6d04116b9cdadf93ad7405a1d5db15f035c3dd#diff-62481efeab60b6a2fc21d34271288c3fL205)
> 
> In the previous commit, the script was being appended to the document. It is no longer. Here is the previous commit line:
> https://github.com/square/react-square-payment-form/blob/27533de09bc192ed4b60ffbdb2d40dd248e0de65/src/components/SquarePaymentForm.tsx#L205

I forked your code and ran your dev branch locally and still got the same issue 
![image](https://user-images.githubusercontent.com/20847319/92339086-4eff7280-f082-11ea-9c26-437730af4e8d.png)

**Comment by spenweb** [comment]
@HarounAns , unfortunately I was not able to load my locally built version of this package so I ended up manually adding the `document.body.appendChild(script);` statement manually to the latest (v0.7.0) package directly in my `node_modules` directory here: `node_modules/react-square-payment-form/lib/components/SquarePaymentForm.js`. This is definitely temporary, but once I added the statement at the end of the `loadSqPaymentFormLibrary` function, the payment form loads.

**Comment by stephtaylor** [comment]
Thank you so much @HarounAns and @spenweb for pointing this issue out and investigating! The PR looks good so I'll publish a new package shortly.
