### ISSUE TITLE
Styling the input fields

### ISSUE THREAD

**Issue by codefist** [square/react-square-payment-form#85]
I apologize for my ignorance, but I cannot figure out how to style the input fields.  Any sort of example would go a million miles in clearing it up.

**Comment by stephtaylor** [comment]
If you want to update the input form styles you can pass a [inputStyles](https://github.com/square/react-square-payment-form/blob/master/src/components/SquarePaymentForm.tsx#L375) prop.

All allowed styles can be found [here](https://developer.squareup.com/docs/api/paymentform#datatype-inputstyleobjects).

If you want to update other attributes, you can override the class name styling mentioned [here](https://square.github.io/react-square-payment-form/docs/customization#change-the-default-styles).

We can definitely update the docs to make this option customization to find. Thanks for calling this out!
