### ISSUE TITLE
Typescript requires formId and apiWrapper properties to be set

### ISSUE THREAD

**Issue by markafox** [square/react-square-payment-form#87]
The formId and apiWrapper properties are required properties but set by defaults.  Typescript requires that these properties be explicitly set because they are not marked as optional.

Because none of the demos or the quick start use these properties it is confusing for programmers using typescript.  

They should either be included in the demos and quick start or marked as optional.

**Comment by Xabadu** [comment]
Hey @markafox,

Thanks for reaching out and bringing this to our attention. I agree, it should be one of those options. We'll take a look at it and update this thread.
