### ISSUE TITLE
Digital wallet methods stay as 'loading' in the context

### ISSUE THREAD

**Issue by cm-datrics** [square/react-square-payment-form#89]
![image](https://user-images.githubusercontent.com/70591489/94348644-de6ec480-0035-11eb-8cc9-a5bfcbccafdf.png)

It seems that even after the methods supported callback is called with all the different methods, informing me that apple pay is not supported etc, the context still says applePayState is loading

Because of this the 'loadingView' that I give to the components like `<GooglePayButton>` persists, rather than showing the actual button if supported or the unavailableView if not.

Any ideas on why this is happening?

**Comment by cm-datrics** [comment]
Looking through the source code, I realise this is because I have supplied my own custom `methodsSupported` prop to the `SquarePaymentForm` and thus the default `methodsSupported` (which is responsible for setting the context values from 'loading' to 'ready' or 'unavailable') is now not being called. Perhaps it would be good to still call the default `methodsSupported` even if a custom prop is supplied - similar to how the `paymentFormLoaded` default is called even if a `paymentFormLoaded` prop is supplied. 

Happy to raise a PR for this if you think it would be a good idea

**Comment by stephtaylor** [comment]
Hi @cm-datrics, thanks for calling this out. It seems like a good idea to me and I'm happy to review the PR when it's ready.

**Comment by cm-datrics** [comment]
Thanks @stephtaylor , made one [here](https://github.com/square/react-square-payment-form/pull/90).

**Comment by stephtaylor** [comment]
@cm-datrics the changes should be available in 0.7.2 Let me know if you run into any issues.
