### ISSUE TITLE
Unable to add line items

### ISSUE THREAD

**Issue by derekbking** [square/react-square-payment-form#93]
Hello,

I want to associate the items purchased with a given transaction. I have attempted to add the line items to my createPaymentRequest function. However, I do not see this reflected on square when reviewing the transaction. Is this an issue with the way I am using the react-square-payment-form package?

`return {
      requestShippingAddress: true,
      requestBillingInfo: true,
      currencyCode: 'USD',
      countryCode: 'US',
      shippingContact: {
        ....
      },
      total: {
        label: "REMOVED",
        amount: '2',
        pending: false,
      },
      lineItems: [
        {
          label: 'Some item here',
          amount: '1',
          pending: false,
        },
        {
          label: 'Another line item here',
          amount: '1',
          pending: false,
        },
      ],
    };`

Thanks!

**Comment by stephtaylor** [comment]
The `lineItems` field in `createPaymentRequest` is used to show items in the digital wallet UI (see [docs](https://developer.squareup.com/docs/api/paymentform#paymentform-paymentrequestobjects) for more info).

If you want to associate items with a given transaction, you can leverage the [Orders API](https://developer.squareup.com/reference/square/orders-api). You then would pass both the order id and payment source when you create the payment ([example API call](https://developer.squareup.com/docs/orders-api/pay-for-orders#using-the-payments-api)) 

Hope that helps!

**Comment by derekbking** [comment]
Thank you for the clarification. Figuring orders out has been a headache for me and I got it working much easier knowing this. Thanks again!
