### ISSUE TITLE
disable prop for CreditCardSubmitButton

### ISSUE THREAD

**Issue by raptoria** [square/react-square-payment-form#96]
I'd love to be able to pass a prop to the CreditCardSubmitButton so I can disable it (not allow the button to be pressed) if there are errors in the form, eg. user hasn't entered an email address.

**Comment by maxbeatty** [comment]
while you're waiting on #99 to ship, you could create a [customized button](https://square.github.io/react-square-payment-form/docs/customization#control-when-the-nonce-is-requested)
