### ISSUE TITLE
Expose SquarePaymentForm State as Context

### ISSUE THREAD

**Issue by MStreet3** [square/react-square-payment-form#97]
Hello,
I may be overlooking a simple solution, but I would to either create the PR or submit a feature request where the state of the `SquarePaymentForm` is exposed via context.  For example If I render a component like the following:

```js
function CardInput() {
	const context = React.useContext(SquareContext);
	return (
		<React.Fragment>
			<SimpleCard />

			<Button fullWidth color='primary' onClick={() => context.onCreateNonce()}>
				{'SAVE CARD'}
			</Button>
		</React.Fragment>
	);
}
```

I have the issue that the `Button` component renders before the `SimpleCard` is completed.  I would like to just track the state of the `SquarePaymentForm` like so:

```js
function CardInput() {
	const context = React.useContext(SquareContext);
        if(context.formLoaded && context.paymentForm){
	  return (
		  <React.Fragment>
			  <SimpleCard />
 
			  <Button fullWidth color='primary' onClick={() => context.onCreateNonce()}>
				  {'SAVE CARD'}
			  </Button>
		  </React.Fragment>
	  );
      }
      // handle some other states ...
      return null;
}
```

Alternatively, is there an existing way to know the status of the form and show an appropriate UI?

Cheers

**Comment by MStreet3** [comment]
https://github.com/square/react-square-payment-form/pull/98

**Comment by maxbeatty** [comment]
The [`paymentFormLoaded` prop](https://square.github.io/react-square-payment-form/docs/components/SquarePaymentForm) will provide that information as you've sorta figured out in your PR. 

```jsx
function PaymentForm() {
  const [formLoaded, setFormLoaded] = React.useState(false)

  return (
    <SqPaymentForm paymentFormLoaded={() => setFormLoaded(true)} >
      <CardInput isReady={formLoaded} />
    </SqPaymentForm>
  )
}
```

I think there's a loose assumption that your `SqPaymentForm` component won't be too far away from payment method components like `SimpleCard`. If that's not the case, I think it's reasonable to expose `formLoaded` on the context.

**Comment by MStreet3** [comment]
Ahh okay thanks. Yea that's reasonable, my eyes missed that prop for sure. Thanks a lot.

**Comment by MStreet3** [comment]
@maxbeatty I finally got a chance to try this and unfortunately it throws an error for me:

`SqPaymentForm initialized without a payment method.`

Here's a codesandbox with an implementation.  I removed the application id, but once that's replaced the error shows in the console.

https://codesandbox.io/s/nostalgic-firefly-8g4ry?file=/src/App.js

**Comment by maxbeatty** [comment]
SqPaymentForm needs `SimpleCard` to exist so it can set up the payment method. (Underneath the hood, a `div` is populated with iframes so Square handles sensitive data, like credit card numbers, instead of you.) You're conditionally rendering the `SimpleCard` which explains the error- before the payment form is ready, there are no payment methods.

```jsx
if (isReady) {
    return (
      <React.Fragment>
        <SimpleCard />
        <button onClick={() => context.onCreateNonce()}>{"SAVE CARD"}</button>
      </React.Fragment>
    );
  }
  return "Loading...";
  ```

Since [`SimpleCard` is just an empty `div` to start](https://github.com/square/react-square-payment-form/blob/166db10a8c18a262a6dfd8da64e5fad73336d421/src/components/SimpleCard.tsx#L15), you could just conditionally render the button to allow the payment method to exist when initializing.

```jsx
return (
    <React.Fragment>
      <SimpleCard />
      {isReady ? (
        <button onClick={() => context.onCreateNonce()}>{"SAVE CARD"}</button>
      ) : (
        "Loading..."
      )}
    </React.Fragment>
  );
  ```

Another path forward is to use CSS classes to control the display of elements based on state.  Hope this helps!

**Comment by MStreet3** [comment]
Ok, got it! Makes sense.. the div needs to exist to load the iframe, but will just be empty until the iframe is loaded.  yup yup, and the sandbox works now.  So it's actually the non-null components that need to wait, not the `<SimpleCard />`.

Thanks a lot for the help.
